### ISSUE TITLE
How to show coordinates?

### ISSUE THREAD

**Issue by lekpkd** [hexlo/minecraft-bedrock-server#1]
I can't enable show coordinates, please help

**Comment by hexlo** [comment]
1. In your world's directory, locate the file named `server.properties`. 
2. Make sure you allow cheats by editing the line: `allow-cheats=true`. 
3. Then turn down your container and start it again: `docker compose down` and `docker compose up -d --force-recreate`
4. In game, you can now enable cheats (which show coordinates is). In the in-game chat, type `/gamerule showcoordinates true` 
5. Enjoy!

**Comment by lekpkd** [comment]
Thank you so much!
