### ISSUE TITLE
Missing "How to update" 

### ISSUE THREAD

**Issue by MrHobbits** [hexlo/minecraft-bedrock-server#3]
Hiya, I'm inexperienced with this docker minecraft stuff,

However, I've got it setup to choose 'latest', however even after multiple restarts the container isn't updating to the latest version. 

Is there a 'how to update when it's not automatically updating' section you could write?

I see in the .scripts folder that there are a couple scripts to check and update to the latest version, but they're not in the container I have. Do I have to just start over, or is there an alternate solution?

**Comment by Psycastria** [comment]
I am having exactly the same issue. I'm running Minecraft Bedrock Server on Synology NAS which was working fine, until minecraft was updated to a new version. Restarted the container many times, but no change.

**Comment by compumark** [comment]
Hi, you need to redeploy the server. Meaning to grab a new image. 
Within portainer you can redeploy and select reload image. 
Within Synology container manager you can click on images and there are your images listed. You will find a message next to the version number, that a new version is available. You can click that. It will download the new version, delete the old and create a new container with the same name. 
The data on the mapped folders will remain and will not be deleted.

**Comment by MrHobbits** [comment]
Can you provide a walkthrough for this method? Whenever I try to redeploy
it, it's starting the whole process over again asking for the powers and
variables, etc.

**Comment by hexlo** [comment]
Sorry for the late reply. To redeploy the server and making sure it's grabbing the latest image, try the following (in the terminal of your server, in the directory where the docker-compose.yml file is):

`docker compose pull` This will pull the latest image.
`docker compose up -d --force-recreate` This line will recreate the container using the now updated image.
As a one-liner: `docker compose pull && docker compose up -d --force-recreate`

As a side note, in certain circumstances, there can be a delay between the client updating to a newer version and the server version being made available for this image to use.

There is also another possible delay between client and server versions updating as this image is built every hour, so if you update the client and try pulling the latest server version, there might be a mismatch.

Hope this helps. Let me know if you are still experiencing issues.
