### ISSUE TITLE
Update to 1.21.40

### ISSUE THREAD

**Issue by 00107** [hexlo/minecraft-bedrock-server#4]
Hello, thank you very much for this repo! Is an update to 1.21.40 in the works? Or can I somehow update the Bedrock server to this version myself? My son is already very impatient. ;)

**Comment by hexlo** [comment]
Hey there. There is an issue getting the latest version. I'm looking into it.

**Comment by hexlo** [comment]
The issue should be fixed. It is now updating to the latest version and is built every hour. Let me know if you have any other issues.

**Comment by 00107** [comment]
Perfect! Update is done, server is running on 1.21.42. Thanks a lot!!
